/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as MeetingsMeetingIdRouteImport } from './routes/meetings.$meetingId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsMeetingIdRoute = MeetingsMeetingIdRouteImport.update({
  id: '/$meetingId',
  path: '/$meetingId',
  getParentRoute: () => MeetingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/meetings': typeof MeetingsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/meetings/$meetingId': typeof MeetingsMeetingIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/meetings': typeof MeetingsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/meetings/$meetingId': typeof MeetingsMeetingIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/meetings': typeof MeetingsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/meetings/$meetingId': typeof MeetingsMeetingIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/meetings'
    | '/settings'
    | '/meetings/$meetingId'
    | '/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/meetings'
    | '/settings'
    | '/meetings/$meetingId'
    | '/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/meetings'
    | '/settings'
    | '/meetings/$meetingId'
    | '/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MeetingsRoute: typeof MeetingsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/$meetingId': {
      id: '/meetings/$meetingId'
      path: '/$meetingId'
      fullPath: '/meetings/$meetingId'
      preLoaderRoute: typeof MeetingsMeetingIdRouteImport
      parentRoute: typeof MeetingsRoute
    }
  }
}

interface MeetingsRouteChildren {
  MeetingsMeetingIdRoute: typeof MeetingsMeetingIdRoute
}

const MeetingsRouteChildren: MeetingsRouteChildren = {
  MeetingsMeetingIdRoute: MeetingsMeetingIdRoute,
}

const MeetingsRouteWithChildren = MeetingsRoute._addFileChildren(
  MeetingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MeetingsRoute: MeetingsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  RunsRunIdRoute: RunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
